# Generated by Django 3.1 on 2021-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210228_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
